[versions]
agp = "8.13.0"
kotlin = "2.2.20"
googleServicesPlugin = "4.4.2"
crashlyticsPlugin = "3.0.4"
performancePlugin = "1.4.2"
coreKtx = "1.16.0"
firebaseBom = "33.15.0"
junit = "4.13.2"
strikt = "0.35.1"
mockito = "5.4.0"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2025.09.00"
navigationCompose = "2.9.0"
coroutines = "1.10.2"
koinBom = "4.1.0"
playServices = "21.3.0"
room = "2.7.1"
material3 = "1.3.2"
mapsCompose = "6.6.0"
mapsecrets = "2.0.1"
credentials = "1.5.0"
googleIdentity = "1.1.1"
okhttp = "4.12.0"
retrofit = "3.0.0"
serialization = "1.8.1"
chucker = "4.2.0"
accompanist = "0.37.3"
morfly-bottomsheet = "0.1.0"
coil = "2.7.0"
coreSplashScreen = "1.0.1"
appcompat = "1.7.1"
inAppUpdate = "1.3.1"
playReview = "2.0.2"
statsig = "4.42.2"
composeScreenshot = "0.0.1-alpha12"

[libraries]
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
coroutines-testing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.7" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-icons = { group = "androidx.compose.material", name = "material-icons-extended" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
morfly-bottomsheet = { module = "io.morfly.compose:advanced-bottomsheet-material3", version.ref = "morfly-bottomsheet" }
composeunstyled = { module = "com.composables:core", version = "1.43.1" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-config = { module = "com.google.firebase:firebase-config" }

amplitude = { module = "com.amplitude:analytics-android", version = "1.22.2" }
amplitude-sessionReplay = { module = "com.amplitude:plugin-session-replay-android", version = "0.20.15" }

maps = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
maps-secrets-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "mapsecrets" }

credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
# optional - needed for credentials support from play services, for devices running Android 13 and below.
credentials-playServices = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
credentials-googleIdentity = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleIdentity" }

playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }
play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie = { module = "com.airbnb.android:lottie-compose", version = "6.6.6" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version = "2.5.1" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
strikt = { module = "io.strikt:strikt-core", version.ref = "strikt" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }

androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashScreen" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

inAppUpdateCompose = { group = "se.warting.in-app-update", name = "in-app-update-compose", version.ref = "inAppUpdate" }
inAppUpdateCompose-material = { group = "se.warting.in-app-update", name = "in-app-update-compose-mui", version.ref = "inAppUpdate" }
statsig-sdk = { group = "com.statsig", name = "android-sdk", version.ref = "statsig" }

compose-screenshot-validation = { module = "com.android.compose.screenshot:screenshot-validation-api", version.ref = "composeScreenshot" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
firebasePerformance = { id = "com.google.firebase.firebase-perf", version.ref = "performancePlugin" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.20-2.0.2" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-screenshot = { id = "com.android.compose.screenshot", version.ref = "composeScreenshot" }

